version: '3.8'

services:
  frontend:
    # image: ${DOCKER_USERNAME}/learnlab-frontend:latest
    image: udaykirandasari/learnlab-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - learnlab-network
    
  backend:
    # image: ${DOCKER_USERNAME}/learnlab-backend:latest
    image: udaykirandasari/learnlab-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
    networks:
      - learnlab-network
    

volumes:
  postgres_data:
    name: learnlab_postgres_data_prod

networks:
  learnlab-network:
    name: learnlab_network_production
    driver: bridge