name: 2. Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
  


env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY}}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}
  UPSTASH_VECTOR_REST_URL: ${{ secrets.UPSTASH_VECTOR_REST_URL }}
  UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.UPSTASH_VECTOR_REST_TOKEN }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
  ELEVENLABS_VOICE_ID_1: ${{ secrets.ELEVENLABS_VOICE_ID_1 }}
  ELEVENLABS_VOICE_ID_2: ${{ secrets.ELEVENLABS_VOICE_ID_2 }}

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 4: Configure Docker layer cache
      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 5: Build and push backend Docker image
      - name: Build and push backend Docker image
        env:
          DOCKER_BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/learnlab-backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          target: production
          push: true
          tags: |
            
            ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        
      # Step 6: Build and push frontend Docker image
      - name: Build and push frontend Docker image
        env:
          DOCKER_FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/learnlab-frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          target: production
          push: true
          tags: |
            
            ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}